package com.C23PS326.icket.model.provinsi


object DataProvinsi {
    val dataprovinsi = listOf(
        Provinsi(
            1,
            "Bali",
            "Denpasar",
            "Provinsi Bali adalah sebuah provinsi di Indonesia yang terletak di Pulau Bali. Bali terkenal sebagai salah satu destinasi pariwisata terbaik di dunia dengan keindahan alamnya yang menakjubkan, budaya yang kaya, dan pantai-pantai yang indah. Ibukota provinsi ini adalah Kota Denpasar. Bali memiliki sejumlah objek wisata populer seperti Pantai Kuta, Ubud yang terkenal dengan seni dan budayanya, Tanah Lot yang terletak di atas laut, dan Pura Besakih sebagai pura terbesar dan terpenting di Bali. Selain itu, Bali juga memiliki tradisi dan upacara adat yang khas seperti Upacara Kuningan, Ngaben (upacara kremasi), dan Ogoh-ogoh pada hari raya Nyepi. Bali juga terkenal dengan kerajinan tangan seperti ukiran kayu, batik, dan perak. Dengan keunikan dan keindahannya, Bali menjadi tujuan wisata yang sangat populer baik bagi wisatawan lokal maupun mancanegara.",
            "https://image.urlaubspiraten.de/640/image/upload/v1603282722/mediavault_images/ihjatwhtozn7ljfgtad7.jpg"
        ),
        Provinsi(
            2,
            "Nanggroe Aceh Darussalam",
            "Banda Aceh",
            "sebuah provinsi di Indonesia yang terletak di ujung barat Pulau Sumatra. Kota utama dan ibu kota provinsi ini adalah Banda Aceh. Aceh memiliki sejarah dan budaya yang kaya, dengan pengaruh dari berbagai kerajaan dan kebudayaan yang pernah berkuasa di wilayah ini. Sejarah Aceh mencakup berbagai periode, mulai dari Kerajaan Samudera Pasai pada abad ke-13 hingga masa penjajahan oleh Belanda. Aceh juga dikenal sebagai pusat perdagangan rempah-rempah dan Islam di Asia Tenggara. Pada abad ke-17, Aceh menjadi kerajaan Islam yang kuat dan melawan serangan kolonial Belanda dalam Perang Aceh.",
            "https://www.indonesia.travel/content/dam/indtravelrevamp/id-id/destinasi/banda-aceh/image-1.jpg"
        ),
        Provinsi(
            3,
            "Bangka Belitung",
            "Pangkal Pinang",
            "Provinsi Kepulauan Bangka Belitung adalah sebuah provinsi di Indonesia yang terdiri dari dua pulau utama yaitu Pulau Bangka dan Pulau Belitung serta pulau-pulau kecil lainnya. Bangka Belitung terletak di bagian timur Pulau Sumatra, dekat dengan Provinsi Sumatra Selatan. Posisi geografis provinsi ini adalah 1º50′ – 3º10′ LS dan 105º – 108º BT. Bangka Belitung dikenal sebagai daerah penghasil timah, memiliki pantai yang indah dan kerukunan antar etnis. Ibu kota provinsi ini ialah Pangkalpinang. Pemerintahan provinsi ini disahkan pada tanggal 9 Februari 2001.",
            "https://www.tempatwisata.pro/media/uploads/3064/83444209afef85d5519fd60c2839a43b.jpg"
        ),
        Provinsi(
            4,
            "Banten",
            "Serang",
            "Provinsi Banten adalah sebuah provinsi di Pulau Jawa, Indonesia. Ibukotanya adalah Kota Serang. Provinsi Banten terletak di bagian barat Pulau Jawa dan berbatasan dengan Laut Jawa di sebelah utara, Provinsi DKI Jakarta di sebelah timur, Provinsi Jawa Barat di sebelah selatan dan barat daya, serta Selat Sunda di sebelah barat. Provinsi Banten memiliki sejarah yang kaya dan pernah menjadi bagian dari Kerajaan Banten yang berpengaruh pada masa lalu",
            "https://asset.kompas.com/crops/_i1RkpLoZ-G0TAXkDKoLf-9Gnp0=/23x11:964x639/750x500/data/photo/2022/03/12/622ca58e77830.jpg"
        ),
        Provinsi(
            5,
            "Bengkulu",
            "Bengkulu",
            "Bengkulu adalah ibu kota Provinsi Bengkulu, Indonesia. Kota ini merupakan kota terbesar kedua di pantai barat Pulau Sumatra, setelah Kota Padang. Sebelumnya kawasan ini suatu kesatuan dengan Kesultanan Palembang Darussalam, Kemudian dikuasai Inggris sebelum diserahkan kepada Belanda.",
            "https://storage.googleapis.com/finansialku_media/wordpress_media/2020/04/9d37ba7e-top-5-tempat-wisata-di-bengkulu-yang-menarik-dikunjungi-untuk-couple-traveler-00-finansialku.jpg",
        ),
        Provinsi(
            6,
            "Daerah Istimewa Yogyakarta",
            "Ibu Kota Yogyakarta",
            "Provinsi Yogyakarta adalah sebuah provinsi di Indonesia yang terletak di bagian selatan Pulau Jawa. Provinsi ini memiliki status istimewa karena merupakan satu-satunya provinsi di Indonesia yang masih mempertahankan sistem monarki. Yogyakarta juga dikenal sebagai pusat budaya, pendidikan, dan pariwisata.  Secara geografis, Yogyakarta terletak di tengah-tengah Pulau Jawa dan berbatasan dengan Provinsi Jawa Tengah di sebelah barat dan Provinsi Jawa Timur di sebelah timur. Yogyakarta juga memiliki pantai di bagian selatannya, seperti Pantai Parangtritis yang terkenal.  Kota Yogyakarta, ibu kota provinsi, adalah pusat kegiatan sosial, politik, dan ekonomi.",
            "https://www.kotajogja.com/wp-content/uploads/2019/09/jakarta-post.jpg",
        ),
        Provinsi(
            7,
            "Gorontalo",
            "Gorontalo",
            "Provinsi Gorontalo adalah sebuah provinsi yang terletak di bagian utara Pulau Sulawesi, Indonesia. Ibukotanya adalah Kota Gorontalo. Provinsi ini berbatasan langsung dengan Laut Sulawesi di sebelah utara, Provinsi Sulawesi Utara di sebelah timur, Provinsi Sulawesi Tengah di sebelah selatan, dan Provinsi Sulawesi Barat di sebelah barat.  Gorontalo terkenal dengan keindahan alamnya, terutama pantai-pantai yang eksotis dan pegunungan yang mempesona. ",
            "https://www.celebes.co/wp-content/uploads/2019/04/Wisata-Gorontalo.jpg",
        ),
        Provinsi(
            8,
            "DKI Jakarta",
            "Jakarta",
            "Provinsi Jakarta adalah provinsi di Indonesia yang terletak di Pulau Jawa. Jakarta juga merupakan ibu kota negara Indonesia. Provinsi ini memiliki luas wilayah sekitar 661,52 kilometer persegi dan terbagi menjadi lima kota administratif, yaitu Jakarta Pusat, Jakarta Utara, Jakarta Selatan, Jakarta Barat, dan Jakarta Timur.Karena statusnya sebagai ibu kota, Jakarta juga menjadi pusat pemerintahan dan pusat kegiatan bisnis. Banyak perusahaan nasional dan internasional memiliki kantor pusat atau cabang di Jakarta. Selain itu, Jakarta juga menjadi tujuan bagi banyak orang yang mencari peluang kerja dan pendidikan yang lebih baik.Sebagai ibu kota negara, Jakarta memiliki peran penting dalam perkembangan Indonesia. Kota ini menjadi tempat pertemuan para pemimpin negara, konferensi internasional, dan acara budaya yang penting. Jakarta juga menawarkan berbagai fasilitas dan layanan modern yang membuatnya menjadi destinasi penting bagi wisatawan dan penduduk setempat.",
            "https://www.bakpiamutiarajogja.com/wp-content/uploads/2018/08/bangunan-ikonik-jakarta.jpg",
        ),
        Provinsi(
            9,
            "Jambi",
            "Jambi",
            "Jambi adalah sebuah kota di Pulau Sumatra, Indonesia sekaligus merupakan ibu kota dari provinsi Jambi. Kota ini merupakan enklave dari kabupaten Muaro Jambi dan dibelah oleh sungai terpanjang di Sumatra yang bernama Batang Hari, kedua kawasan tersebut terhubung oleh jembatan Aur Duri.",
            "https://panduanwisata.id/wp-content/uploads/2022/08/Jembatan-Gentala-Arasy.jpg",
        ),
        Provinsi(
            10,
            "Jawa Barat",
            "Bandung",
            "Jawa Barat adalah salah satu provinsi di Pulau Jawa, Indonesia. Ibukota provinsi ini adalah Kota Bandung. Jawa Barat memiliki luas wilayah sekitar 34.377,48 kilometer persegi dan merupakan salah satu provinsi terpadat di Indonesia. Provinsi Jawa Barat berbatasan dengan Provinsi DKI Jakarta dan Provinsi Banten di sebelah barat, Laut Jawa di sebelah utara, Provinsi Jawa Tengah di sebelah timur, serta Provinsi Sumatra Selatan dan Provinsi Bengkulu di sebelah selatan.  Jawa Barat memiliki beragam potensi wisata, mulai dari wisata alam, sejarah, budaya, hingga kuliner. ",
            "https://cdn-2.tstatic.net/tribunnews/foto/bank/images/indonesiatravel-gedung-sate-salah-satu-ikon-kota-bandung.jpg",
        ),
        Provinsi(
            11,
            "Jawa Tengah",
            "Semarang",
            "Provinsi Jawa Tengah adalah salah satu provinsi di Indonesia yang terletak di Pulau Jawa. Ibu kotanya adalah Semarang. Provinsi Jawa Tengah memiliki luas wilayah sekitar 32.548 kilometer persegi dan merupakan provinsi dengan jumlah penduduk terbesar kedua setelah Jawa Barat.  Jawa Tengah memiliki kekayaan budaya dan sejarah yang kaya.",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Borobudur_Temple.jpg/1280px-Borobudur_Temple.jpg",
        ),
        Provinsi(
            12,
            "Jawa Timur",
            "Surabaya",
            "Provinsi Jawa Timur adalah salah satu provinsi di Indonesia yang terletak di bagian timur pulau Jawa. Ibu kota provinsi ini adalah Surabaya, kota terbesar kedua di Indonesia setelah Jakarta. Jawa Timur memiliki luas wilayah sekitar 47.922,59 km² dan merupakan provinsi dengan jumlah penduduk terbanyak di Indonesia.  Jawa Timur memiliki kekayaan budaya, sejarah, dan alam yang beragam.",
            "https://img.inews.co.id/media/822/files/inews_new/2022/09/16/patung_surabaya.jpg",
        ),
        Provinsi(
            13,
            "Kalimantan Barat",
            "Pontianak",
            "Daerah Kalimantan Barat termasuk salah satu daerah yang dapat dijuluki provinsi \"Seribu Sungai\". Julukan ini selaras dengan kondisi geografis yang mempunyai ratusan sungai besar dan kecil yang di antaranya dapat dan sering dilayari. Beberapa sungai besar sampai saat ini masih merupakan urat nadi dan jalur utama untuk angkutan daerah pedalaman, walaupun prasarana jalan darat telah dapat menjangkau sebagian besar kecamatan.  Kalimantan Barat berbatasan darat dengan negara bagian Sarawak, Malaysia.Walaupun sebagian kecil wilayah Kalimantan Barat merupakan perairan laut, akan tetapi Kalimantan Barat memiliki puluhan pulau besar dan kecil (sebagian tidak berpenghuni) yang tersebar sepanjang Selat Karimata dan Laut Natuna yang berbatasan dengan wilayah Provinsi Kepulauan Riau.",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Dayak_Dancers.jpg/1920px-Dayak_Dancers.jpg",
        ),
        Provinsi(
            14,
            "Kalimantan Selatan",
            "Banjarbaru",
            "Provinsi Kalimantan Selatan adalah salah satu provinsi yang terletak di pulau Kalimantan, Indonesia. Ibu kota provinsi ini adalah Banjarmasin. Kalimantan Selatan memiliki luas wilayah sekitar 38.744 kilometer persegi dan merupakan salah satu provinsi terbesar di Indonesia.",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Banjarmasin_floating_market%2C_2018.jpg/1920px-Banjarmasin_floating_market%2C_2018.jpg",
        ),
        Provinsi(
            15,
            "Kalimantan Tengah",
            "Palangkaraya",
            "Kalimantan Tengah adalah sebuah provinsi di pulau Kalimantan, Indonesia. Ibu kotanya adalah Palangkaraya. Provinsi Kalimantan Tengah terletak di tengah pulau Kalimantan dan berbatasan dengan provinsi Kalimantan Utara di sebelah utara, provinsi Kalimantan Timur di sebelah timur, provinsi Kalimantan Selatan di sebelah selatan, dan provinsi Kalimantan Barat di sebelah barat.  Kalimantan Tengah memiliki kekayaan alam yang melimpah, termasuk hutan hujan tropis, sungai-sungai yang besar seperti Sungai Kahayan dan Sungai Kapuas, dan flora dan fauna yang beragam. Provinsi ini juga kaya akan budaya dan tradisi suku Dayak, yang merupakan suku asli yang mendiami wilayah tersebut.",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Lawang_Sakepeng_180505003.JPG/1920px-Lawang_Sakepeng_180505003.JPG",
        ),
        Provinsi(
            16,
            "Kalimantan Timur",
            "Samarinda",
            "Indonesia. Ibu kota provinsi ini adalah Kota Samarinda. Kalimantan Timur berbatasan dengan provinsi Kalimantan Utara di sebelah utara, Selat Makassar di sebelah timur, provinsi Kalimantan Selatan di sebelah selatan, serta provinsi Kalimantan Barat di sebelah barat.  Kalimantan Timur memiliki potensi alam yang melimpah, termasuk sumber daya alam seperti minyak bumi, gas alam, batu bara, dan berbagai macam kekayaan hayati. Provinsi ini juga memiliki keanekaragaman budaya dan suku-suku asli seperti suku Dayak, suku Banjar, suku Kutai, dan suku Benuaq.",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Tari_Pemung_Tawai_180619002.JPG/1920px-Tari_Pemung_Tawai_180619002.JPG",
        ),
        Provinsi(
            17,
            "Kalimantan Utara",
            "Tanjung Selor",
            "Provinsi Kalimantan Utara adalah sebuah provinsi di Indonesia yang terletak di bagian utara pulau Kalimantan. Provinsi ini berbatasan dengan provinsi Kalimantan Tengah di sebelah selatan, Laut Sulawesi di sebelah utara, provinsi Kalimantan Timur di sebelah timur, serta negara Brunei Darussalam di sebelah barat.Kalimantan Utara terkenal dengan keindahan alamnya yang meliputi hutan hujan tropis, pantai-pantai yang indah, dan keanekaragaman hayati yang kaya. Beberapa tempat wisata populer di provinsi ini antara lain Taman Nasional Kayan Mentarang, Pantai Amal, Pulau Derawan, dan Gunung Buluan. Aktivitas wisata yang populer di Kalimantan Utara meliputi penjelajahan alam, menyelam, snorkeling, dan mempelajari budaya suku-suku Dayak yang merupakan penduduk asli Kalimantan Utara.  Selain potensi wisata alamnya, Kalimantan Utara juga merupakan pusat perdagangan dan pelabuhan yang penting di wilayah timur Indonesia. Provinsi ini juga memiliki kekayaan sumber daya alam seperti minyak bumi, gas alam, dan hasil hutan.  Provinsi Kalimantan Utara didirikan pada tahun 2012 setelah pemekaran dari provinsi Kalimantan Timur. Pembentukan provinsi ini bertujuan untuk mempercepat pembangunan dan pemerataan pembangunan di wilayah tersebut.",
            "https://kompaspedia.kompas.id/wp-content/uploads/2020/11/20130426PRA01.jpg",
        ),
        Provinsi(
            18,
            "Kepulauan Riau",
            "Tanjung Pinang",
            "Asal usul nama Kepulauan Riau berasal dari nama Riau. Riau diduga berasal kata \"riuh\" yang berarti ramai. Hal ini dikarenakan daerah Kepulauan Riau dahulunya merupakan pusat perdagangan dan keramaian. Lalu nama ini berkembang dengan digunakannya nama Riau pada nama Kesultanan Lingga. Pada masa kolonial, kata Riau dituliskan \"Riouw\", sesuai dengan ejaan bahasa Belanda.  Setelah proklamasi kemerdekaan, wilayah Riau (Kepulauan Riau saat ini) disatukan dengan wilayah Kesultanan Siak di daratan Sumatra. Dahulunya, hal ini dilakukan karena gerakan Ganyang Malaysia sehingga mempermudah hubungan dari wilayah kepulauan ke daratan Sumatra.",
            "https://upload.wikimedia.org/wikipedia/commons/4/46/Jembatan_Tengku_Fisabilillah_%28jembatan_I%29.jpg",
        ),
        Provinsi(
            19,
            "Lampung",
            "Bandar Lampung",
            "Provinsi Lampung adalah provinsi yang terletak pada bagian sebelah paling ujung tenggara pulau Sumatera. Provinsi Lampung lahir pada tanggal 18 Maret 1964 dengan ditetapkannya Peraturan Pemerintah Nomor 3/1964 yang kemudian menjadi Undang-undang Nomor 14 tahun 1964. Sebelum itu Provinsi Lampung merupakan Karesidenan yang tergabung dengan Provinsi Sumatera Selatan. Provinsi Lampung beribukota di Bandar Lampung, yang merupakan gabungan dari kota kembar Tanjungkarang dan Telukbetung memiliki wilayah yang relatif luas, dan menyimpan potensi kelautan. Pelabuhan utamanya bernama Panjang dan Bakauheni serta pelabuhan nelayan seperti Pasar Ikan (Telukbetung), Tarahan, dan Kalianda di Teluk Lampung.",
            "https://blog.tiket.com/wp-content/uploads/2019/05/4.-Siger-Tower.jpg",
        ),
        Provinsi(
            20,
            "Maluku",
            "Ambon",
            "Provinsi Maluku adalah sebuah provinsi di Indonesia. Terletak di bagian timur Indonesia, provinsi ini terdiri dari wilayah kepulauan yang meliputi pulau-pulau di sekitar Kepulauan Maluku. Ibu kota provinsi Maluku adalah Kota Ambon. Provinsi Maluku terbagi menjadi dua kabupaten yaitu Kabupaten Maluku Tengah dan Kabupaten Maluku Tenggara, serta satu kota yaitu Kota Ambon. Selain itu, provinsi Maluku juga memiliki beberapa pulau besar lainnya seperti Seram, Buru, dan Kei. Provinsi Maluku terkenal dengan keindahan alamnya, termasuk pantai, pegunungan, dan kekayaan bawah lautnya.",
            "https://upload.wikimedia.org/wikipedia/commons/b/bf/Gong_Perdamaian_Dunia_Ambon.jpg",
        ),
        Provinsi(
            21,
            "Maluku Utara",
            "Sofifi",
            "Provinsi Maluku Utara adalah sebuah provinsi di Indonesia. Ibu kota provinsi ini adalah Sofifi, yang terletak di Pulau Halmahera. Provinsi Maluku Utara terbentuk pada tahun 1999 setelah pemekaran dari Provinsi Maluku. Wilayahnya terdiri dari beberapa pulau utama, seperti Halmahera, Ternate, Tidore, dan pulau-pulau kecil di sekitarnya. Provinsi ini memiliki kekayaan alam yang melimpah, termasuk sumber daya mineral, perikanan, dan keindahan alam yang menarik wisatawan.",
            "https://upload.wikimedia.org/wikipedia/commons/4/46/Surga_rempah_rempah.jpg",
        ),
        Provinsi(
            22,
            "Nusa Tenggara Barat",
            "Mataram",
            "Provinsi Nusa Tenggara Barat adalah sebuah provinsi yang terletak di Pulau Nusa Tenggara, Indonesia. Ibu kota provinsi ini adalah Kota Mataram. Nusa Tenggara Barat memiliki kekayaan alam yang indah, termasuk pantai-pantai berpasir putih, gunung-gunung, dan pulau-pulau eksotis.",
            "https://cdn-2.tstatic.net/lombok/foto/bank/images/Mataram-Metro.jpg",
        ),
        Provinsi(
            23,
            "Nusa Tenggara Timur",
            "Kupang",
            "Nusa Tenggara Timur (NTT) adalah salah satu provinsi di Indonesia. Provinsi ini terletak di bagian timur Indonesia, tepatnya di Pulau Timor dan sebagian besar Kepulauan Nusa Tenggara. Ibu kota NTT adalah Kota Kupang. Provinsi Nusa Tenggara Timur terdiri dari berbagai pulau yang termasuk di antaranya adalah Pulau Timor, Pulau Flores, Pulau Sumba, Pulau Alor, dan Pulau Rote. NTT memiliki kekayaan alam, budaya, dan sejarah yang kaya serta merupakan tujuan wisata yang populer di Indonesia.",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Kampung_Adat_Praijing%2C_Sumba_Barat.jpg/1920px-Kampung_Adat_Praijing%2C_Sumba_Barat.jpg",
        ),
        Provinsi(
            24,
            "Papua",
            "Jayapura",
            "Provinsi Papua adalah sebuah provinsi di Indonesia yang terletak di bagian timur Pulau Papua. Provinsi ini dibagi menjadi dua provinsi yaitu Papua dan Papua Barat sejak tahun 2003. Ibu kota provinsi Papua adalah Kota Jayapura, sedangkan ibu kota provinsi Papua Barat adalah Kota Manokwari.",
            "https://lh5.googleusercontent.com/p/AF1QipNMX5U8hggwOC7k0S6DWqChr_U5IuOByrXsayUZ=w548-h318-n-k-no",
        ),
        Provinsi(
            25,
            "Papua Barat",
            "Manokwari",
            "Provinsi Papua Barat adalah sebuah provinsi di Indonesia. Ibu kota provinsi ini adalah Kota Manokwari. Provinsi Papua Barat terletak di bagian barat Pulau Papua dan berbatasan dengan Provinsi Papua di sebelah timur. Papua Barat memiliki luas wilayah sekitar 114.566 kilometer persegi dan merupakan provinsi terbesar kedua di Indonesia setelah Provinsi Papua.",
            "https://asset.kompas.com/crops/r3_KIYWkhK6aC_l0SHoBrK_rBcM=/0x0:719x479/750x500/data/photo/2021/10/31/617e75d9cabfd.jpg",
        ),
        Provinsi(
            26,
            "Papua Barat Daya",
            "Sorong",
            "Papua Barat Daya adalah sebuah provinsi di Indonesia, dan merupakan pemekaran dari Papua Barat. Meski bernama Barat Daya, namun provinsi ini terletak di bagian barat laut Pulau Papua, sebuah contoh misnomer.",
            "https://asset.kompas.com/crops/umkF_hkf3VDvIZrMxwEASEquB8M=/0x104:600x504/750x500/data/photo/2022/11/18/6376ba3da3966.png",
        ),
        Provinsi(
            27,
            "Papua Pegunungan",
            "Jayawijaya",
            "Papua Pegunungan adalah sebuah provinsi di Indonesia yang dimekarkan dari provinsi Papua pada sidang Paripurna DPR RI pada tanggal 30 Juni 2022. Ibu kotanya berkedudukan di Kabupaten Jayawijaya.",
            "https://upload.wikimedia.org/wikipedia/commons/f/fe/Taman_Wio_Silimo_Wamena.jpg",
        ),
        Provinsi(
            28,
            "Papua Selatan",
            "Merauke",
            "Papua Selatan adalah salah satu provinsi di Indonesia yang telah dimekarkan dari Provinsi Papua. Ibu kotanya berada di Kabupaten Merauke, tepatnya di Kota Terpadu Mandiri Salor di Distrik Kurik sekitar 60 km dari Kota Merauke.",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Taman_0_Kilometer_Merauke_-_Sabang.jpg/1920px-Taman_0_Kilometer_Merauke_-_Sabang.jpg",
        ),
        Provinsi(
            29,
            "Papua Tengah",
            "Nabire",
            "Papua Tengah adalah sebuah provinsi di Indonesia yang telah dimekarkan dari provinsi Papua pada tahun 2022.Ibukota Provinsi ini berada di Kabupaten Nabire.Papua Tengah dimekarkan dari Provinsi Papua bersama dua provinsi lainnya yakni Papua Pegunungan dan Papua Selatan pada 30 Juni 2022 berdasarkan Undang-Undang Nomor 15 Tahun 2022.Cakupan wilayah Papua Tengah kira-kira sesuai dengan wilayah adat Mee Pago dan Saireri.  Kabupaten Nabire di bagian utara Papua Tengah merupakan dataran rendah berbatasan langsung dengan Taman Nasional Teluk Cenderawasih yang memiliki potensi pariwisata bahari seperti terumbu karang, pulau-pulau berpasir putih dan hiu paus.Bagian tengah Papua Tengah terdapat kawasan Danau Paniai dan Pegunungan Jayawijaya. Di provinsi ini terdapat gunung tertinggi di Indonesia yaitu Puncak Jaya serta tambang emas Grasberg yang dioperasikan oleh Freeport Indonesia.Bagian selatan Papua Tengah adalah Kabupaten Mimika dengan ibu kotanya Timika yang merupakan salah satu kota besar di Pulau Papua. Sedangkan topografi Mimika berupa rawa-rawa, sungai, dan pantai.",
            "https://upload.wikimedia.org/wikipedia/commons/5/54/Kota_Timika.jpg",
        ),
        Provinsi(
            30,
            "Riau",
            "Pekanbaru",
            "Riau adalah sebuah provinsi di Indonesia yang terletak di bagian tengah pantai timur pulau Sumatra. Wilayah pesisirnya berbatasan dengan Selat Malaka. Hingga tahun 2004, provinsi ini juga meliputi Kepulauan Riau, sekelompok besar pulau-pulau kecil yang terletak di sebelah Timur Sumatra dan sebelah Selatan Singapura.",
            "https://www.lamudi.co.id/journal/wp-content/uploads/2022/10/Rumah-adat-selaso-jatuh-kembar-Riau.jpg",
        ),
        Provinsi(
            31,
            "Sulawesi Barat",
            "Mamuju",
            "Provinsi Sulawesi Barat adalah sebuah provinsi di Indonesia yang terletak di pulau Sulawesi. Ibu kotanya adalah Mamuju. Provinsi Sulawesi Barat secara resmi didirikan pada tahun 2004 setelah dipisahkan dari Provinsi Sulawesi Selatan. Wilayah ini memiliki luas sekitar 16.796,19 kilometer persegi dan terbagi menjadi lima kabupaten, yaitu Mamuju, Mamuju Tengah, Polewali Mandar, Majene, dan Mamasa. Sulawesi Barat memiliki potensi alam yang kaya, seperti pantai yang indah, hutan tropis, dan pegunungan yang mempesona. Suku-suku yang mendiami provinsi ini antara lain suku Mandar, suku Bugis, suku Toraja, dan suku Makassar.",
            "https://upload.wikimedia.org/wikipedia/commons/9/9b/Raiyani_Muharramah-Tugu_Gong_Perdamaian_Mamuju_DSCF8348.jpg",
        ),
        Provinsi(
            32,
            "Sulawesi Selatan",
            "Makassar",
            "Provinsi Sulawesi Selatan adalah sebuah provinsi di Indonesia. Ibu kotanya adalah Makassar. Provinsi ini terletak di bagian selatan Pulau Sulawesi dan merupakan salah satu provinsi yang paling padat penduduknya di Indonesia. Sulawesi Selatan memiliki beragam budaya dan etnis, seperti suku Bugis, Makassar, Toraja, Mandar, dan banyak lagi. Wilayah ini juga terkenal dengan keindahan alamnya, termasuk Taman Nasional Bantimurung-Bulusaraung, Taman Nasional Wakatobi, dan Taman Nasional Lore Lindu.",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Kete%27_Kesu%27_Toraja.jpg/1920px-Kete%27_Kesu%27_Toraja.jpg",
        ),
        Provinsi(
            33,
            "Sulawesi Tengah",
            "Palu",
            "Provinsi Sulawesi Tengah adalah salah satu provinsi yang terletak di Pulau Sulawesi, Indonesia. Ibu kota provinsi ini adalah Kota Palu. Sulawesi Tengah memiliki luas wilayah sekitar 61.841 kilometer persegi dan terbagi menjadi 12 kabupaten dan 1 kota.  Provinsi Sulawesi Tengah memiliki beragam keindahan alam, seperti pegunungan, danau, sungai, serta pantai-pantai yang menarik. Beberapa objek wisata populer di Sulawesi Tengah antara lain Taman Nasional Lore Lindu, Danau Poso, Taman Nasional Togean, Pantai Talise, dan banyak lagi.  Sulawesi Tengah juga memiliki beragam budaya dan suku-suku yang berbeda, seperti suku Kaili, Toli-Toli, dan Banggai. Masing-masing suku memiliki kekayaan budaya, tradisi, dan adat istiadat yang unik.  Provinsi Sulawesi Tengah memiliki sektor ekonomi yang didominasi oleh pertanian, perkebunan, perikanan, dan pariwisata. Produk pertanian utama di daerah ini antara lain padi, jagung, kakao, dan kelapa. Selain itu, Sulawesi Tengah juga memiliki potensi tambang, seperti tambang nikel dan emas.  Secara administratif, provinsi Sulawesi Tengah terbagi menjadi 12 kabupaten yaitu Banggai, Banggai Kepulauan, Buol, Donggala, Morowali, Parigi Moutong, Poso, Sigi, Tojo Una-Una, Toli-Toli, Tolitoli Utara, dan Kota Palu.",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Tari_Masalo.jpg/1920px-Tari_Masalo.jpg",
        ),
        Provinsi(
            34,
            "Sulawesi Tenggara",
            "Kendari",
            "Provinsi Sulawesi Tenggara adalah sebuah provinsi di Indonesia yang terletak di bagian tenggara Pulau Sulawesi. Ibu kotanya adalah Kota Kendari. Sulawesi Tenggara memiliki luas wilayah sekitar 38.140 kilometer persegi dan merupakan provinsi yang relatif baru, diresmikan pada tanggal 27 September 1964. Wilayah provinsi ini terdiri dari daratan dan pulau-pulau kecil di sekitarnya.  Provinsi Sulawesi Tenggara terbagi menjadi 10 kabupaten/kota, yaitu Kabupaten Bombana, Kabupaten Buton, Kabupaten Buton Utara, Kabupaten Buton Selatan, Kabupaten Kolaka, Kabupaten Kolaka Timur, Kabupaten Kolaka Utara, Kabupaten Konawe, Kabupaten Konawe Selatan, dan Kota Kendari. Wilayah ini kaya akan sumber daya alam, terutama dalam sektor pertambangan dan perkebunan.  Sulawesi Tenggara memiliki budaya yang beragam, dengan mayoritas penduduknya berasal dari suku-suku seperti Tolaki, Buton, Muna, dan lain-lain. Bahasa resmi yang digunakan di provinsi ini adalah Bahasa Indonesia, namun terdapat juga bahasa-bahasa daerah yang masih digunakan oleh masyarakat setempat.",
            "https://3.bp.blogspot.com/-RHsbl-yyU3c/VtrvmohtfjI/AAAAAAAAAd4/HydeagRgw50/s1600/28.jpg",
        ),
        Provinsi(
            35,
            "Sulawesi Utara",
            "Manado",
            "Provinsi Sulawesi Utara adalah sebuah provinsi di Indonesia. Ibukotanya adalah Kota Manado. Provinsi ini terletak di bagian utara Pulau Sulawesi dan berbatasan dengan Laut Filipina di sebelah utara, Provinsi Gorontalo di sebelah barat, Provinsi Sulawesi Tengah di sebelah selatan, dan Provinsi Maluku Utara di sebelah timur. Sulawesi Utara memiliki keanekaragaman budaya, adat istiadat, dan alam yang kaya, termasuk Taman Nasional Bunaken yang terkenal dengan keindahan bawah lautnya.",
            "https://imujio.com/wp-content/uploads/2019/11/Kebudayaan-Sulawesi-Utara.jpg",
        ),
        Provinsi(
            36,
            "Sumatera Barat",
            "Padang",
            "Provinsi Sumatera Barat terkenal sebagai salah satu destinasi wisata di Indonesia. Terletak di pesisir barat pulau Sumatra, wilayah ini dikaruniai keindahan panorama alam, keunikan adat istiadat, ragam kuliner, kesenian, dan situs bersejarah.",
            "https://awsimages.detik.net.id/community/media/visual/2022/06/18/tiga-spot-asyik-untuk-menikmati-dan-mengabadikan-jam-gadang-1_169.jpeg?w=1200",
        ),
        Provinsi(
            37,
            "Sumatera Selatan",
            "Palembang",
            "Adalah provinsi di Indonesia yang terletak di bagian Selatan pulau Sumatra. Ibu kota Sumatra Selatan berada di kota Palembang, dan pada tahun 2021 penduduk provinsi ini berjumlah 8.550.849 jiwa.",
            "https://assets.pikiran-rakyat.com/crop/0x0:0x0/x/photo/2021/12/23/2444060385.jpg",
        ),
        Provinsi(
            38,
            "Sumatera Utara",
            "Medan",
            "Sumatera Utara adalah sebuah provinsi yang terletak di Pulau Sumatera, berbatasan dengan Aceh di sebelah utara dan dengan Sumatera Barat serta Riau di sebelah selatan.\n" +
                    "\n" +
                    "Provinsi ini terutama merupakan kampung halaman suku bangsa Batak, yang hidup di pegunungan dan suku bangsa Melayu yang hidup di daerah pesisir timur. Selain itu juga ada suku bangsa Nias di pesisir Barat Sumatera, Mandailing, Jawa dan Tionghoa.",
            "https://cdnwpedutorenews.gramedia.net/wp-content/uploads/2022/01/02201551/Rumah-Adat-Sumatera-Utara-2.jpg",
        ),
    )
}